version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbmain
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    restart: always
    build: ./api/
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
    depends_on:
      - db
  ui:
    restart: always
    build: ./ui/
    volumes:
      - './ui:/ui'
      - '/ui/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development